export const categories_clueless = [
    { id : 'all', name: 'All Resources', count: 11 },
    { id : 'experts', name: 'Experts', count: 3 },
    { id : 'events', name: 'Events', count: 4 },
    { id : 'news', name: 'News', count: 4 },
];

export const categories_motivated = [
    { id: 'all', name: 'All Resources', count: 12 },
    { id: 'research', name: 'Research', count: 4 },
    { id: 'funding', name: 'Funding', count: 4 },
    { id: 'events', name: 'Events', count: 4 },
];

export const categories_hesitant = [
    { id : 'all', name: 'All Resources', count: 11 },
    { id : 'experts', name: 'Experts', count: 3 },
    { id : 'funding', name: 'Funding', count: 4 },
    { id : 'news', name: 'News', count: 4 },
];

export const resources_clueless = [
    // EXPERTS
    {
        id: 1,
        name: "Prof. Dr. Dietmar Grichnik",
        institution: "Swiss Institute for Small and Medium-Sized Enterprises (KMU-HSG)",
        description: "Expert in SME management and entrepreneurship, specializing in innovation management and financing strategies for small businesses in Switzerland.",
        tags: ["SME Management", "Entrepreneurship", "Innovation"],
        type: "experts",
        imageUrl: "/images/dietmar.png",
        number: "+41 71 224 72 01",
    },
    {
        id: 2,
        name: "Prof. Dr. Thomas Zellweger",
        institution: "Center for Family Business (CFB-HSG)",
        description: "Leading expert on family businesses in Switzerland, focusing on succession planning, governance, and long-term innovation strategies.",
        tags: ["Family Business", "Succession Planning", "Governance"],
        type: "experts",
        imageUrl: "/images/thomas.jpeg",
        number: "+41 71 224 71 00",
    },
    {
        "id": 3,
        "name": "Prof. Dr. Oliver Gassmann",
        "institution": "Institute for Technology Management (ITEM-HSG)",
        "description": "Professor for Technology Management with a focus on Innovation Management, Business Model Innovation, and Strategic Innovation Leadership.",
        "tags": ["Innovation Management", "Business Model Innovation", "Open Innovation", "Technology Management"],
        "type": "experts",
        "imageUrl": "/images/oliver.webp",
        "number": "+41 71 224 7221"
    },

    // EVENTS
    {
        id: 4,
        name: "St. Gallen Innovation Day",
        institution: "Switzerland Innovation Park Ost (SIPOst)",
        description: "Annual event connecting SMEs with innovation experts and researchers, featuring workshops on practical innovation methods and funding opportunities for smaller businesses.",
        tags: ["Networking", "Innovation", "Knowledge Transfer"],
        type: "events",
        imageUrl: "/images/sipost.jpg",
        number: "+41 71 277 20 40",
    },
    {
        id: 5,
        name: "Digital Transformation Workshop Series",
        institution: "\"IT rockt!\" St.Gallen",
        description: "Monthly workshops specifically designed for SMEs looking to implement digital solutions without extensive resources. Includes hands-on training and peer exchange opportunities.",
        tags: ["Digitalization", "Practical Skills", "Peer Learning"],
        type: "events",
        imageUrl: "/images/itrockt.jpg",
        number: "+41 71 278 25 25",
    },
    {
        id: 6,
        name: "Eastern Switzerland Business Forum",
        institution: "Cantonal Trade Association St.Gallen (KGV)",
        description: "Quarterly event bringing together SME owners and managers from Eastern Switzerland to discuss current challenges, regulatory updates, and collaboration opportunities.",
        tags: ["Regional Networking", "SME Management", "Policy Updates"],
        type: "events",
        imageUrl: "/images/cantontrade.jpg",
        number: "+41 71 228 10 40",
    },
    {
        id: 7,
        name: "Innosuisse Funding Information Day",
        institution: "Innosuisse",
        description: "Bi-annual event providing SMEs with information on available innovation funding programs, application procedures, and success stories from previous grant recipients.",
        tags: ["Funding", "Grants", "Innovation Support"],
        type: "events",
        imageUrl: "/images/inno.png",
        number: "+41 58 461 61 61",
    },

    // NEWS
    {
        id: 8,
        name: "KMU Innovation Monitor",
        institution: "Swiss Institute for Small and Medium-Sized Enterprises (KMU-HSG)",
        description: "Quarterly report analyzing innovation trends and challenges specifically for Swiss SMEs, with practical recommendations and regional benchmarking.",
        tags: ["Market Research", "Innovation Trends", "Benchmarking"],
        type: "news",
        imageUrl: "/images/kmu.webp",
        number: "kmu-hsg@unisg.ch ",
    },
    {
        id: 9,
        name: "Digital SME Newsletter",
        institution: "Eastern Switzerland University of Applied Sciences (OST)",
        description: "Monthly newsletter highlighting digital transformation case studies from local SMEs, featuring practical implementation tips and low-cost technology solutions.",
        tags: ["Digital Transformation", "Case Studies", "Practical Tips"],
        type: "news",
        imageUrl: "/images/ost.jpg",
        number: "info@ost.ch",
    },
    {
        id: 10,
        name: "Circular Economy for SMEs",
        institution: "Circular Economy – Institute of Management & Strategy (IoMS-HSG)",
        description: "Bi-monthly publication showcasing sustainability innovations from regional SMEs, with guides on implementing circular business models on limited resources.",
        tags: ["Sustainability", "Circular Economy", "Business Models"],
        type: "news",
        imageUrl: "/images/ioms.jpg",
        number: "ifb-info@unisg.ch",
    },
    {
        id: 11,
        name: "SwissMEM Industry Report",
        institution: "Swissmem",
        description: "Quarterly analysis of developments in the Swiss mechanical, electrical, and metal industries, with special section dedicated to SME opportunities and challenges.",
        tags: ["Industry Analysis", "Manufacturing", "Engineering"],
        type: "news",
        imageUrl: "/images/swissmem.jpg",
        number: "info@swissmem.ch",
    },
];

export const resources_motivated = [
    // RESEARCH
    {
        id: 1,
        name: "Applied Innovation Projects",
        institution: "Institute of Technology and Innovation Management (ITEM-HSG)",
        description: "Collaborative research program where SMEs can partner with HSG researchers to solve specific innovation challenges. Projects typically last 6-12 months with shared resources.",
        tags: ["Collaborative Research", "Innovation Methods", "Academic Partnership"],
        type: "research",
        imageUrl: "",
        number: "item@unisg.ch",
    },
    {
        id: 2,
        name: "Industry 4.0 Lab Access",
        institution: "Eastern Switzerland University of Applied Sciences (OST)",
        description: "SMEs can access state-of-the-art manufacturing technology labs to prototype and test new products or processes with guidance from OST researchers.",
        tags: ["Prototyping", "Industry 4.0", "Manufacturing"],
        type: "research",
        imageUrl: "",
        number: "engineering@ost.ch",
    },
    {
        id: 3,
        name: "RhySearch Materials Analysis",
        institution: "RhySearch Innovation Center",
        description: "Specialized materials testing and analysis services for manufacturing SMEs, with expert consulting on material optimization and selection for innovative products.",
        tags: ["Materials Science", "Product Development", "Testing"],
        type: "research",
        imageUrl: "",
        number: "info@rhysearch.ch",
    },
    {
        id: 4,
        name: "Circular Economy Research Partnership",
        institution: "Circular Economy – Institute of Management & Strategy (IoMS-HSG)",
        description: "Research program helping SMEs redesign products and business models following circular economy principles, with implementation support and impact assessment.",
        tags: ["Sustainability", "Circular Economy", "Business Model Innovation"],
        type: "research",
        imageUrl: "",
        number: "info@unisg.ch",
    },

    // FUNDING
    {
        id: 5,
        name: "Innovation Cheque",
        institution: "Innosuisse",
        description: "Vouchers worth up to CHF 15,000 for SMEs to conduct preliminary studies and test innovative ideas in collaboration with a research partner, with simplified application process.",
        tags: ["Initial Funding", "Feasibility Study", "Low Barrier"],
        type: "funding",
        imageUrl: "",
        number: "info@innosuisse.ch",
    },
    {
        id: 6,
        name: "Innovation Projects with Partners",
        institution: "Innosuisse",
        description: "Co-funding for joint innovation projects between SMEs and research institutions. Innosuisse covers research partner costs while SME contributes own resources and expertise.",
        tags: ["Co-funding", "R&D Partnership", "Product Development"],
        type: "funding",
        imageUrl: "",
        number: "info@innosuisse.ch",
    },
    {
        id: 7,
        name: "Swiss Accelerator Program",
        institution: "Innosuisse",
        description: "Tailored support package for SMEs with market-ready innovations, including coaching, international market entry support, and connections to potential investors.",
        tags: ["Market Entry", "Scaling", "International Expansion"],
        type: "funding",
        imageUrl: "",
        number: "info@innosuisse.ch",
    },
    {
        id: 8,
        name: "Regional Innovation Support",
        institution: "Economic Promotion Canton of St. Gallen",
        description: "Financial and advisory support for innovation projects that strengthen the regional economy, with focus on SMEs implementing significant technological advancements.",
        tags: ["Regional Development", "Technology Adoption", "Advisory Support"],
        type: "funding",
        imageUrl: "",
        number: "info@wirtschaftsg.ch",
    },

    // EVENTS
    {
        id: 9,
        name: "Advanced Manufacturing Symposium",
        institution: "Empa",
        description: "Annual symposium on cutting-edge manufacturing technologies with workshops specifically for SMEs on implementing advanced techniques with limited resources.",
        tags: ["Advanced Manufacturing", "Technology Transfer", "Networking"],
        type: "events",
        imageUrl: "",
        number: "October 2025",
    },
    {
        id: 10,
        name: "Innovation Bootcamp",
        institution: "Innovation Network Eastern Switzerland",
        description: "Intensive 3-day program for SME teams to develop new product or service concepts under guidance of innovation experts, with pitch session to potential funders.",
        tags: ["Intensive Workshop", "Product Development", "Ideation"],
        type: "events",
        imageUrl: "",
        number: "Quarterly (Feb, May, Aug, Nov)",
    },
    {
        id: 11,
        name: "International Market Entry Workshop",
        institution: "Chamber of Commerce St.Gallen-Appenzell (IHK)",
        description: "Specialized workshop series helping innovative SMEs prepare for international expansion, covering legal, marketing, and operational aspects of different markets.",
        tags: ["International Expansion", "Export", "Market Research"],
        type: "events",
        imageUrl: "",
        number: "Bi-monthly",
    },
    {
        id: 12,
        name: "MedTech Innovation Conference",
        institution: "St.Gallen Health",
        description: "Conference connecting SMEs in the medical technology sector with healthcare providers, researchers, and potential partners to develop innovative healthcare solutions.",
        tags: ["Medical Technology", "Healthcare Innovation", "Partnership Building"],
        type: "events",
        imageUrl: "",
        number: "September 2025",
    },
];

export const resources_hesitant = [
    // EXPERTS
    {
        id: 1,
        name: "Prof. Dr. Dietmar Grichnik",
        institution: "Swiss Institute for Small and Medium-Sized Enterprises (KMU-HSG)",
        description: "Expert in SME management and entrepreneurship, specializing in innovation management and financing strategies for small businesses in Switzerland.",
        tags: ["SME Management", "Entrepreneurship", "Innovation"],
        type: "experts",
        imageUrl: "/images/dietmar.png",
        number: "+41 71 224 72 01",
    },
    {
        id: 2,
        name: "Prof. Dr. Thomas Zellweger",
        institution: "Center for Family Business (CFB-HSG)",
        description: "Leading expert on family businesses in Switzerland, focusing on succession planning, governance, and long-term innovation strategies.",
        tags: ["Family Business", "Succession Planning", "Governance"],
        type: "experts",
        imageUrl: "/images/thomas.jpeg",
        number: "+41 71 224 71 00",
    },
    {
        "id": 3,
        "name": "Prof. Dr. Oliver Gassmann",
        "institution": "Institute for Technology Management (ITEM-HSG)",
        "description": "Professor for Technology Management with a focus on Innovation Management, Business Model Innovation, and Strategic Innovation Leadership.",
        "tags": ["Innovation Management", "Business Model Innovation", "Open Innovation", "Technology Management"],
        "type": "experts",
        "imageUrl": "/images/oliver.webp",
        "number": "+41 71 224 7221"
    },


    // NEWS
    {
        id: 9,
        name: "KMU Innovation Monitor",
        institution: "Swiss Institute for Small and Medium-Sized Enterprises (KMU-HSG)",
        description: "Quarterly report analyzing innovation trends and challenges specifically for Swiss SMEs, with practical recommendations and regional benchmarking.",
        tags: ["Market Research", "Innovation Trends", "Benchmarking"],
        type: "news",
        imageUrl: "/images/kmu.webp",
        number: "kmu-hsg@unisg.ch ",
    },
    {
        id: 10,
        name: "Digital SME Newsletter",
        institution: "Eastern Switzerland University of Applied Sciences (OST)",
        description: "Monthly newsletter highlighting digital transformation case studies from local SMEs, featuring practical implementation tips and low-cost technology solutions.",
        tags: ["Digital Transformation", "Case Studies", "Practical Tips"],
        type: "news",
        imageUrl: "/images/ost.jpg",
        number: "info@ost.ch",
    },
    {
        id: 11,
        name: "Circular Economy for SMEs",
        institution: "Circular Economy – Institute of Management & Strategy (IoMS-HSG)",
        description: "Bi-monthly publication showcasing sustainability innovations from regional SMEs, with guides on implementing circular business models on limited resources.",
        tags: ["Sustainability", "Circular Economy", "Business Models"],
        type: "news",
        imageUrl: "/images/ioms.jpg",
        number: "ifb-info@unisg.ch",
    },
    {
        id: 12,
        name: "SwissMEM Industry Report",
        institution: "Swissmem",
        description: "Quarterly analysis of developments in the Swiss mechanical, electrical, and metal industries, with special section dedicated to SME opportunities and challenges.",
        tags: ["Industry Analysis", "Manufacturing", "Engineering"],
        type: "news",
        imageUrl: "/images/swissmem.jpg",
        number: "info@swissmem.ch",
    },

];
